name: CI
on:
  push:
    branches:
      - master

jobs:
  Windows:
    name: Windows Node.js ${{ matrix.node-version }}
    # Containers must run in Linux based operating systems
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: npm run build
      - run: npm run build:doc

  Ubuntu:
    name: Ubuntu Node.js ${{ matrix.node-version }}
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: npm run build
      - run: npm run build:doc
